[package]
name = "vft-service"
version = "1.1.0"
license = "MIT"
edition = "2021"

[dependencies]
gstd = "1.9.0"
log = "*"
sails-rs = "0.9.0"

[dev-dependencies]
env_logger = "*"

[features]
wasm-binary = []
