[package]
name = "vmt-service"
version = "1.1.0"
license = "MIT"
edition = "2021"

[dependencies]
gstd = "=1.8.1"
log = "*"
sails-rs = "=0.8.1"

[dev-dependencies]
env_logger = "*"

[features]
wasm-binary = []

